http:
  routers:
    # sfcc sitegenesis sitemap rules
    # SFCC-sitegenesis-UK-Site-ID is the sitemap id of the sitegenesis site
    # to enable sitemap generation set environment variable  GENERATE_SITEMAP to "true"
    # traefik v1: traefik.sitegenesis-sitemap.frontend.rule: Host:corporate.${ENVIRONMENT_FQDN:-docker.localhost};Path:/sitemap_index.xml,/{file:sitemap(.*).xml.gz};AddPrefix:/blueprint/servlet/service/sitemap/SFCC-sitegenesis-UK-Site-ID
    cae-live-sfcc-sitemap:
      # need a lower priority than any landing page route but higher than the servlet rule
      priority: 40
      entrypoints:
        - web-access-secure
        - web-access-insecure
      rule: Host(`sitegenesis.{{ env "ENVIRONMENT_FQDN" | default "docker.localhost"}}`) && Path(`/sitemap_index.xml`,`/{file:sitemap(.*).xml.gz}`)
      service: cae-live
      middlewares:
        - cae-live-sfcc-sitemap-add-prefix@file

  middlewares:
    cae-live-sfcc-sitemap-add-prefix:
      addPrefix:
        prefix: "/blueprint/servlet/service/sitemap/SFCC-sitegenesis-UK-Site-ID"
