tls:
  certificates:
    - certFile: /etc/traefik/certificates/traefik.crt
      keyFile: /etc/traefik/certificates/traefik.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certificates/traefik.crt
        keyFile: /etc/traefik/certificates/traefik.key
