http:
  routers:
    headless-server-preview:
      priority: 1
      entrypoints:
        - web-access-secure
        - web-access-insecure
      rule: Host(`headless-server-preview.{{ env "ENVIRONMENT_FQDN" | default "docker.localhost"}}`) && PathPrefix(`/graphql`,`/caas`,`/previewurl`,`/preview`)
      service: headless-server-preview

  services:
    headless-server-preview:
      loadBalancer:
        servers:
          - url: http://headless-server-preview:8080
