http:
  routers:
    site-manager:
      entrypoints:
        - web-access-secure
        - web-access-insecure
      rule: Host(`site-manager.{{ env "ENVIRONMENT_FQDN" | default "docker.localhost"}}`)
      service: site-manager

  services:
    site-manager:
      loadBalancer:
        servers:
          - url: http://site-manager:80
