http:
  routers:
    studio-client:
      # this priority is required so that the client backend rules are prioritized first
      priority: 50
      entrypoints:
        - web-access-secure
        - web-access-insecure
      rule: Host(`studio.{{ env "ENVIRONMENT_FQDN" | default "docker.localhost"}}`)
      service: studio-client
      middlewares:
        - studio-client-compression@file
  services:
    studio-client:
      loadBalancer:
        servers:
          - url: h2c://studio-client:80
  middlewares:
    studio-client-compression:
      compress: true
